<a href="https://colab.research.google.com/github/khanbaba-ahamaliiev/ITStep-AI/blob/superwised_learning/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [1]:
import numpy as np
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [48]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [20]:
mask = df['embarked'] == 'Q'
df[mask]

     pclass     sex   age  sibsp  parch     fare embarked
5         3    male   NaN      0      0   8.4583        Q
16        3    male   2.0      4      1  29.1250        Q
22        3  female  15.0      0      0   8.0292        Q
28        3  female   NaN      0      0   7.8792        Q
32        3  female   NaN      0      0   7.7500        Q
..      ...     ...   ...    ...    ...      ...      ...
790       3    male   NaN      0      0   7.7500        Q
825       3    male   NaN      0      0   6.9500        Q
828       3    male   NaN      0      0   7.7500        Q
885       3  female  39.0      0      5  29.1250        Q
890       3    male  32.0      0      0   7.7500        Q

[77 rows x 7 columns]

In [22]:
mask.sum()

np.int64(216)

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [25]:
mask = df['pclass'] == 1
mask

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: pclass, Length: 891, dtype: bool

In [30]:
new_df = df[mask]
new_df[['age','sex', 'fare']]

      age     sex     fare
1    38.0  female  71.2833
3    35.0  female  53.1000
6    54.0    male  51.8625
11   58.0  female  26.5500
23   28.0    male  35.5000
..    ...     ...      ...
871  47.0  female  52.5542
872  33.0    male   5.0000
879  56.0  female  83.1583
887  19.0  female  30.0000
889  26.0    male  30.0000

[216 rows x 3 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

In [37]:
mask = (df['age'] < 18) & (df['embarked'] == 'C') & (df['sex'] == 'male')
df[mask]

     pclass   sex    age  sibsp  parch      fare embarked
125       3  male  12.00      1      0   11.2417        C
352       3  male  15.00      1      1    7.2292        C
532       3  male  17.00      1      1    7.2292        C
550       1  male  17.00      0      2  110.8833        C
731       3  male  11.00      0      0   18.7875        C
803       3  male   0.42      0      1    8.5167        C
827       2  male   1.00      0      2   37.0042        C

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [49]:
df['relatives'] = df['sibsp'] + df['parch']
df

     pclass     sex   age  sibsp  parch     fare embarked  relatives
0         3    male  22.0      1      0   7.2500        S          1
1         1  female  38.0      1      0  71.2833        C          1
2         3  female  26.0      0      0   7.9250        S          0
3         1  female  35.0      1      0  53.1000        S          1
4         3    male  35.0      0      0   8.0500        S          0
..      ...     ...   ...    ...    ...      ...      ...        ...
886       2    male  27.0      0      0  13.0000        S          0
887       1  female  19.0      0      0  30.0000        S          0
888       3  female   NaN      1      2  23.4500        S          3
889       1    male  26.0      0      0  30.0000        C          0
890       3    male  32.0      0      0   7.7500        Q          0

[891 rows x 8 columns]

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     891 non-null    int64
 1   sex        891 non-null    object
 2   age        714 non-null    float64
 3   sibsp      891 non-null    int64
 4   parch      891 non-null    int64
 5   fare       891 non-null    float64
 6   embarked   889 non-null    object
 7   relatives  891 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 62.6+ KB

In [51]:
mask_df = df.isnull()
mask_df.sum()

pclass         0
sex            0
age          177
sibsp          0
parch          0
fare           0
embarked       2
relatives      0
dtype: int64

In [56]:
clean_df = df.drop(columns='age')
clean_df

     pclass     sex  sibsp  parch     fare embarked  relatives
0         3    male      1      0   7.2500        S          1
1         1  female      1      0  71.2833        C          1
2         3  female      0      0   7.9250        S          0
3         1  female      1      0  53.1000        S          1
4         3    male      0      0   8.0500        S          0
..      ...     ...    ...    ...      ...      ...        ...
886       2    male      0      0  13.0000        S          0
887       1  female      0      0  30.0000        S          0
888       3  female      1      2  23.4500        S          3
889       1    male      0      0  30.0000        C          0
890       3    male      0      0   7.7500        Q          0

[891 rows x 7 columns]

In [57]:
clean_df.dropna()

     pclass     sex  sibsp  parch     fare embarked  relatives
0         3    male      1      0   7.2500        S          1
1         1  female      1      0  71.2833        C          1
2         3  female      0      0   7.9250        S          0
3         1  female      1      0  53.1000        S          1
4         3    male      0      0   8.0500        S          0
..      ...     ...    ...    ...      ...      ...        ...
886       2    male      0      0  13.0000        S          0
887       1  female      0      0  30.0000        S          0
888       3  female      1      2  23.4500        S          3
889       1    male      0      0  30.0000        C          0
890       3    male      0      0   7.7500        Q          0

[889 rows x 7 columns]